name: Crewmeister-DevOps-Challenge

on:
  release:
    types: [created]
  push:
    branches: [ test ]

jobs:

  Build:
    name: Maven-Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build and verify with Maven
      run: mvn clean verify -e -X

    - name: Package workflow data as artifacts
      run: mkdir staging && cp target/*.jar staging

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

  Scan:
    name: Trivy-Scan
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
