name: Crewmeister-DevOps-Challenge

on:
  release:
    types: [created]
  push:
    branches: [ test ]

jobs:

  Build:
    name: Maven-Build
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: challenge
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and verify with Maven
        uses: s4u/maven-action@v2
        with:
          maven-args: "clean verify -e -X"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/challenge?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: dev
          SPRING_APPLICATION_NAME: app

      - name: Package workflow data as artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

  Scan:
    name: Trivy-Scan
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
